[unstable]
# enable the unstable artifact-dependencies feature, see
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
bindeps = true

[alias]
kbuild = "build -p osmium_kernel --target x86_64-unknown-none"
ktest = "test -p osmium_kernel --target x86_64-unknown-none"
